### ISSUE TITLE
ClickModel is missing from folder tools

### ISSUE THREAD

**Issue by Catherine-Chu** [Jinjiarui/DRSR#1]
It seems that a _click.py_ file which contains class _ClickModel_  is missing  from folder _tools_.
For example, when I ran the _run_data.py_, it tried to import _ClickModel_ from _tools.click_, and raised an _ModuleNotFoundError_ .

`
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf
import numpy as np
import argparse
import os.path as osp
import sys

sys.path.append('../')

from tools.click import ClickModel
from tools.base import *
from tools.utility import *
`

**Comment by Jinjiarui** [comment]
Sorry for the delayed reply. These click models are collected to https://github.com/ULTR-Community/ULTRA. You can refer to the above repo to find these models.
